company_cell/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from company_cell.models import company
from company_cell.views import comp_detail,showCompanies
from django.conf import settings
from django.conf.urls.static import static


app_name='company_cell'
urlpatterns=[

    url(r'^companies$', showCompanies.as_view(), name='showCompanies'),
    # url('applyjob/$',views.applyjob, name='applyjob'),
    url('home/',views.back_home, name='back_home'),
    
    
    path('<slug:pk>/', comp_detail.as_view(), name='comp_detail'),
    path('<slug:comp_id>/<slug:username>/count_stud/',views.count_stud,name='count_stud'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

placement/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls import url
from django.contrib.auth.models import User
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    
    path('admin/', admin.site.urls),
   
    path('company_cell/', include('company_cell.urls')),
    path('registers/',include('registers.urls')),
    path('', include('first_page.urls')),
    path('notification/', include('notification.urls')),
   
   
    
   
 
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/accounts/companies.html
{% load static %}
<html>

<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">


</head>

<body>
<nav>
    <div class="nav-wrapper orange lighten-3">
      <a href="/" class="brand-logo">Placement Portal</a>
     
    </div>
</nav>

  <table class="highlight">
  {% if companies_list %}
  {% for company in companies_list %}
        <thead>
          <tr>
          <th>Company ID</th>
              <th>Company Name</th>
              <th>Job Profile</th>
              <th>No of students applied</th>
              <th>Status</th>
              <th>Apply </th>
          </tr>
        </thead>

        <tbody>
          <tr>
          <td>{{ company.comp_id }}</td>
            <td>{{ company.comp_name }}</td>
            <td>{{ company.job_profile }}</td>
            <td>{{ company.no_of_students_applied }}</td>
            <td>{{ company.comp_status }}</td>
            
            <td><a href="{% url 'company_cell:comp_detail' company.comp_id %}">Apply</a></td>
          </tr>
        </tbody>
        {% endfor %}
    
{% else %}
    <p>No Companies are available.</p>
{% endif %}
      </table>



  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
</body>

</html>

     
          
 
  {% comment %} {% if companies_list %}
    <ul>
    {% for company in companies_list %}
        <li><a href="{% url 'company_cell:comp_detail' company.comp_id %}">{{ company.comp_name }} {{ company.job_profile}} {{ company.comp_id }} {{ company.comp_status }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Companies are available.</p>
{% endif %} {% endcomment %}
 





{% comment %} <html>
    <head>
        <meta charset="UTF-8">
        <title>Companies</title>
    </head>
    <body>
        <h1>List of Companies</h1>
        
        <table border=1>
            <tr>

                <th>Company id</th>
                <th>Company name</th>
                <th>Profile</th>
                <th>Status</th>
                <th>Apply</th>
            </tr>
            {% for company in allCompanies %}
            <tr>
                <td>{{ company.comp_id }}</td>
                <td>{{ company.comp_name }}</td>
                <td>{{ company.job_profile }}</td>
                <td>{{ company.comp_status }}</td>
                <td><a href="{% url 'company_cell:DetailView' %}">REGISTER</a></td>
            </tr>
            {% endfor %}              
        </table>
        
            

        
    </body>
    </html>
 {% endcomment %}

templates/accounts/company1.html
<a href="{% url 'company_cell:showCompanies' %}">BACK TO COMPANIES</a>
<br>
<a href="{% url 'company_cell:back_home' %}">HOME</a>

templates/accounts/company_detail.html
{% load static %}
<!doctype html>
<html lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<head>
  <title>Company-Details</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>

<body id="bg" style="background-image: url('{% static 'images/back2.jpg' %}')";>

  <div>
    <!-- <img src="{% static 'images/comp_back1.jpg' %}"> -->
    
   
  </div> 
  <nav>
    <div class="nav-wrapper orange lighten-3">
      <a href="/" class="brand-logo white-text">Placement Portal</a>
      <!-- <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">JavaScript</a></li>
      </ul> -->
    </div>
  </nav>
  <form action="{% url 'company_cell:count_stud' company.comp_id user.username %}" method="post">
  {% csrf_token %}

  <!-- <div class='container'> -->
   <h5>Company Id: {{ company.comp_id }}</h5>
  <!-- </div> -->
  <h5>Company Name: {{ company.comp_name }}</h5>
  <!-- <input type="text" name="country" value="{{ company.comp_name }}" hidden><br> -->
  <h5>Company Status: {{ company.comp_status }}</h5>
  <h5>Job Profile: {{ company.job_profile }}</h5>
  {{ form.comp_name }}

  <input type="submit" class="waves-effect waves-light btn modal-trigger" value="submit">
  </form> 
  
 
  <script type = "text/javascript"
          src = "https://code.jquery.com/jquery-2.1.1.min.js"></script>           
  <script src = "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

</body>
</html>

templates/accounts/profile.html
{% load static %}
<html>

<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">


</head>

<body>
<nav>
    <div class="nav-wrapper orange lighten-3">
      <a href="/" class="brand-logo">Placement Portal</a>
     
    </div>
</nav>

  <table class="highlight">
  
        <thead>
          <tr>
          <th>Company ID</th>
              <th>Company Name</th>
              <th>Job Profile</th>
              <th>No of students applied</th>
              
          </tr>
        </thead>

        <tbody>
          <tr>
          <td>{{ Student.regno }}</td>
            <td>{{ Student.name }}</td>
            <td>{{ user.regno }}</td>
            <td>{{ Student.regno }}</td>
            
            
            <td><a href="{% url 'company_cell:comp_detail' company.comp_id %}">Apply</a></td>
          </tr>
        </tbody>
      
      </table>



  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
</body>

</html>
{% comment %} <h1>{{ Student.regno }}</h1>
<h1>{{ Student.name }}</h1>

<h1>{{ user.regno }}</h1>
<h1>{{ Student.regno }}</h1> {% endcomment %}

templates/accounts/updated_profile.html
<!DOCTYPE html>
<html>
    <head>
        <title>Profile</title>
    </head>

    <body>
        

        {{ user.name }}
        {{ user.email }}
        {{ user.regno }}
        {{ user.course }}

        <a href="{% url 'update' %}">Update/Edit</a>

     
    </body>

</html>